'sue strict'

export const RIDDLE_STAGE_BEFORE_START = "RS_BEFORE_START";
export const RIDDLE_STAGE_STARTED = "RS_STARTED";
export const RIDDLE_STAGE_INACTIVE = "RS_INACTIVE";
export const RIDDLE_STAGE_INACTIVE_AFTER_ANSWER = "RS_INACTIVE_AFTER_ANSWER";
export const RIDDLE_STAGE_FINISHED = "RS_FINISHED";